server:
  port: 10089
spring:
  application:
    name: crm-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 3500
  MaxAutoRetirsNextServer: 0
  MaxAutoRetirs: 0
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 5000
zuul:
  prefix: /api
